### ISSUE TITLE
Ask about configs

### ISSUE THREAD

**Issue by beikungg** [NLPV2011/So-VITS-SVC-Whisper-V3#1]
Hi Friends，Your method of combining so-vits-svc with whisperv3 has given me great inspiration and help! Thank you very much!
I'm having a little trouble right now. I notice that the parameters in the config file in your code are roughly the same as so-vits-svc4.1, but you changed them from 80 to 128 in "n_mel_channels" and from 22050 to null in "max_mel". Maybe I am a beginner, would like to ask this treatment will make the model better effect?
That's the question that's been bothering me lately,and I would really appreciate it if you could reply to me.

**Comment by NLPV2011** [comment]
Hmm ... This question is interesting. Therefore, I changed "n_mel_channels" from 80 to 128 because 128 is a multiple of 2 (2 x 2 x 2 x 2 x 2 x 2) and so GPU and CPU will work effectively More than 80. Why am I asking "max_mel" to be Null instead of other numbers? We notice this depends on the Sample Rate of Audio, I realize that if the Sample Rate is 44100, Max_MEL will be 22050 and I see the model only the highest note is 22050Hz, so when I put it as Null, we don't do not we do Need to set and recalculate max_mel when the sample rate changes. Should pay attention because this is only a repo that I just do in a sketchy way, so you may need to fix it

**Comment by beikungg** [comment]
thank you very much! I would try this change later,maybe it can work for me as your mentioned!thanks again, and your codes are so helpful.
